name: Run Linter

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    uses: yext/slapshot-reusable-workflows/.github/workflows/run-linting.yml@v1
    with:
      lint_script: npm run lint && npm run prettier-check
