name: Sync Main to Storybook Site Branch

on:
  push:
    branches:
      - main

jobs:
  call_sync_branches:
    uses: yext/slapshot-reusable-workflows/.github/workflows/sync_default_branch.yml@v1
    with:
      target_branch: storybook-site
    secrets:
      caller_github_token: ${{ secrets.GITHUB_TOKEN }}
